create table if not exists public.users (
  id integer generated by default as identity primary key,
  name text not null check (length(btrim(name)) > 0)
);

alter table public.users enable row level security;

grant select, insert, update, delete on public.users to service_role;
grant usage, select on sequence public.users_id_seq to service_role;

insert into public.users (id, name) values (1, 'Alex'), (2, 'Sam')
on conflict (id) do nothing;
select setval('public.users_id_seq', greatest((select coalesce(max(id), 1) from public.users), 1), true);
